In [1]:
import gym
import numpy as np
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [5]:
action_space_size= env.action_space.n
state_space_size= env.observation_space.n

q_table= np.zeros((state_space_size, action_space_size))
print(q_table)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [35]:
num_episodes=10000
max_steps_per_episode=1000

learning_rate= 0.01
discount_factor= 0.99

max_exploration = 1.0
min_exploration = 0.01
exploration_rate_decay= 0.001
exploration = 1.0

In [36]:
rewards_all_episodes= []

for episode in range(num_episodes):
    state= env.reset()
    done=False
    reward_current_episode=0
    for step in range(max_steps_per_episode):
        exploration_threshold= random.uniform(0,1)
        if(exploration_threshold > exploration):
            action=np.argmax(q_table[state, : ])
        else:
            action= env.action_space.sample()
        new_state, reward, done, info= env.step(action)
        
        q_table[state,action]= q_table[state,action]*(1-learning_rate) + learning_rate*(reward + discount_factor* np.max(q_table[new_state,:]))
        
        state=new_state
        reward_current_episode+=reward;
        if done==True:
            break
    exploration= min_exploration + (max_exploration-min_exploration)*np.exp(-exploration_rate_decay*episode)
    rewards_all_episodes.append(reward_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.04
2000 :  0.158
3000 :  0.379
4000 :  0.541
5000 :  0.63
6000 :  0.648
7000 :  0.707
8000 :  0.69
9000 :  0.697
10000 :  0.667


In [38]:
print(q_table)

[[ 0.52979785  0.51608726  0.51768394  0.51597781]
 [ 0.41709023  0.3927828   0.42606525  0.49023609]
 [ 0.46009614  0.46395608  0.4605671   0.46790899]
 [ 0.41598526  0.40711586  0.35537133  0.45587807]
 [ 0.54676095  0.40765809  0.41314075  0.36674873]
 [ 0.          0.          0.          0.        ]
 [ 0.33873035  0.20422533  0.32001094  0.21772987]
 [ 0.          0.          0.          0.        ]
 [ 0.38883228  0.41585004  0.4041694   0.58542598]
 [ 0.44800037  0.64588799  0.49600742  0.47884976]
 [ 0.59772181  0.51265778  0.41592771  0.36323832]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.43435434  0.528442    0.74177134  0.53072444]
 [ 0.7763921   0.87364169  0.81953766  0.81269795]
 [ 0.          0.          0.          0.        ]]


In [37]:
for episode in range(3):
    state=env.reset()
    done=False
    time.sleep(1)
    print(episode)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action= np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward==1:
                print("Reached Goal")
                time.sleep(3)
            else:
                print("Fell in hole")
                time.sleep(3)
            clear_output(wait=True)
            break
        state= new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
Reached Goal
